### ISSUE TITLE
[Feat] 가게 API

### ISSUE THREAD

**Issue by bongbongbon** [bongbongbon/IssueTest#1]
## TODO
- [ ] 컨트롤러 작성
- [ ] 도메인 파일 작성
- [ ] 가게 CRUD 기능
- [ ] 가게 Search 기능
